[theme]
# Primary color for interactive elements like buttons and links
primaryColor="#007BFF"

# Main background color
backgroundColor="#F0F8FF"

# Background color for the sidebar, expanders, and uploader
secondaryBackgroundColor="#E6F2FF"

# Main text color
textColor="#0D3B66"

# Font style (sans serif often looks cleaner with modern themes)
font="sans serif"